Presentation/Animal.Web/Controllers/CategoryTypeController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace Animal.Web.Controllers
{
	public class CategoryTypeController : Base.AuthorizationController
	{
		public static IWebHostEnvironment _webHostEnvironment;
		private readonly IHttpContextAccessor _httpContextAccessor;


		public CategoryTypeController(IWebHostEnvironment webHostEnvironment, IHttpContextAccessor httpContextAccessor) : base(httpContextAccessor)
		{
			_webHostEnvironment = webHostEnvironment;
			_httpContextAccessor = httpContextAccessor;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult GetAllCategories()
		{
			var obj = new AnimalProvider.CategoryType();
			var objList = obj.getAllCategories();

			return View(objList);
		}

		public IActionResult GetCategoryType(int id)
		{
			if (id == 0)
			{
				return View(new Entities.CategoryType());
			}

			var obj = new AnimalProvider.CategoryType();
			var model = obj.getCategoryType(id);

			return View(model);
		}

		[HttpGet]
		public IActionResult addCategoryType()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult AddCategoryType(ViewModel.CategoryType CategoryType)
		{
			if (ModelState.IsValid)
			{
				using var obj = new AnimalProvider.CategoryType();

				if (CategoryType.files.ContentType.Split("/")[1] != "png")
				{
					ModelState.AddModelError("FormValidation", "wrong file type. file type should be png");
					return View(CategoryType);
				}

				string pathToDirectory = _webHostEnvironment.WebRootPath + "\\FileUploads\\";
				string fileName = $"{DateTimeOffset.Now.ToUnixTimeMilliseconds()}.{CategoryType.files.ContentType.Split("/")[1]}";
				string pathToFile = pathToDirectory + fileName;
				string relativePathToFile = "\\FileUploads\\" + fileName;
				//(DateTimeOffset.Now.ToUnixTimeSeconds()) should return the current unix time in milliseconds
				//(CategoryType.files.ContentType.Split("/")[1]) should return "png" as in the extension of the image

				try
				{
					if (CategoryType.files.Length > 0)
					{
						if (!Directory.Exists(pathToDirectory))
						{
							Directory.CreateDirectory(pathToDirectory);
						}
						using (FileStream fileStream = System.IO.File.Create(pathToFile))
						{
							CategoryType.files.CopyTo(fileStream);
							fileStream.Flush();
							fileStream.Close();
						}
					}
					else
					{
						ModelState.AddModelError("FormValidation", "empty or no file sent");
						return View(CategoryType);
					}
				}
				catch (Exception ex)
				{
					ModelState.AddModelError("FormValidation", "an error has occured\n" + ex.Message);
					return View(CategoryType);
				}

				Entities.CategoryType modelSent = new Entities.CategoryType();
				modelSent.Id = CategoryType.Id;
				modelSent.CategoryName = CategoryType.CategoryName;
				modelSent.ImagePath = relativePathToFile;

				if (obj.addCategoryType(modelSent))
				{
					//Success
					ModelState.AddModelError("FormValidation", "Success");
					return View();
				}
				else
				{
					ModelState.AddModelError("FormValidation", "an error has occured");
					return View(CategoryType);
				}
			}
			else
			{
				return View(CategoryType);
			}

		}

		[HttpGet]
		public IActionResult UpdateCategoryType()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult UpdateCategoryType(ViewModel.CategoryType CategoryType)
		{
			if (ModelState.IsValid)
			{
				using var obj = new AnimalProvider.CategoryType();

				if (CategoryType.files.ContentType.Split("/")[1] != "png")
				{
					ModelState.AddModelError("FormValidation", "wrong file type. file type should be png");
					return View(CategoryType);
				}

				//to delete the current categorytype image currently stored
				Entities.CategoryType prevInstance = obj.getCategoryType(CategoryType.Id);
				System.IO.File.Delete(prevInstance.ImagePath);

				string pathToDirectory = _webHostEnvironment.WebRootPath + "\\FileUploads\\";
				string fileName = $"{DateTimeOffset.Now.ToUnixTimeMilliseconds()}.{CategoryType.files.ContentType.Split("/")[1]}";
				string pathToFile = pathToDirectory + fileName;
				string relativePathToFile = "\\FileUploads\\" + fileName;
				//(DateTimeOffset.Now.ToUnixTimeSeconds()) should return the current unix time in milliseconds
				//(CategoryType.files.ContentType.Split("/")[1]) should return "png" as in the extension of the image

				try
				{
					if (CategoryType.files.Length > 0)
					{
						if (!Directory.Exists(pathToDirectory))
						{
							Directory.CreateDirectory(pathToDirectory);
						}
						using (FileStream fileStream = System.IO.File.Create(pathToFile))
						{
							CategoryType.files.CopyTo(fileStream);
							fileStream.Flush();
							fileStream.Close();
						}
					}
					else
					{
						ModelState.AddModelError("FormValidation", "empty or no file sent");
						return View(CategoryType);
					}
				}
				catch (Exception ex)
				{
					ModelState.AddModelError("FormValidation", "an error has occured\n" + ex.Message);
					return View(CategoryType);
				}

				Entities.CategoryType modelSent = new Entities.CategoryType();
				modelSent.Id = CategoryType.Id;
				modelSent.CategoryName = CategoryType.CategoryName;
				modelSent.ImagePath = relativePathToFile;

				if (obj.updateCategoryType(modelSent))
				{
					//Success
					ModelState.AddModelError("FormValidation", "Success");
					return View();
				}
				else
				{
					ModelState.AddModelError("FormValidation", "an error has occured");
					return View(CategoryType);
				}
			}
			else
			{
				return View(CategoryType);
			}
		}

		[HttpGet]
		public IActionResult DeleteCategoryType()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult DeleteCategoryType(int id)
		{
			if (ModelState.IsValid)
			{
				using var obj = new AnimalProvider.CategoryType();

				if (obj.deleteCategoryType(id))
				{
					//Success
					ModelState.AddModelError("FormValidation", "Success");
					return View();
				}
				else
				{
					ModelState.AddModelError("FormValidation", "an error has occured");
					return View(id);
				}
			}
			else
			{
				return View(id);
			}
		}
	}
}

Presentation/Animal.Web/Views/CategoryType/AddCategoryType.cshtml
@model ViewModel.CategoryType
@using Animal.Web.MediaComponents


@using (Html.BeginForm("AddCategoryType", "CategoryType", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = $"formSubmit('{Url.Action("AddCategoryType", "CategoryType")}', this, event);" }))
{
	@Html.AntiForgeryToken()
	<div>@Html.ValidationMessage("FormValidation")</div>

	@Html.TextInput(m=>m.CategoryName)

	@Html.FileInput(m=>m.files)

	@Html.SubmitButton("Submit form")
}

Presentation/Animal.Web/Views/CategoryType/DeleteCategoryType.cshtml
@using Animal.Web.MediaComponents


@using (Html.BeginForm("DeleteCategoryType", "CategoryType", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = $"formSubmit('{Url.Action("DeleteCategoryType", "CategoryType")}', this, event);" }))
{
	@Html.AntiForgeryToken()
	<div>@Html.ValidationMessage("FormValidation")</div>

	@Html.SingleStringInput("id")

	@Html.SubmitButton("Submit form")
}

Presentation/Animal.Web/Views/CategoryType/GetAllCategories.cshtml
@model List<Entities.CategoryType>

<table class="table table-bordered table-striped">
	<thead>
	<th class="p-3">ID</th>
	<th class="p-3">Name</th>
	<th class="p-3">Image</th>
	</thead>

	@{
		foreach (var item in Model)
		{
			<tr>
				<td class="p-3">@item.Id</td>
				<td class="p-3">@item.CategoryName</td>
				<td class="p-3"><img style="width:30px;height:30px;" src="@item.ImagePath" /></td>
				<td class="p-3">
					<a class="text-dark" href="javascript:changeMain('@Url.Action("GetCategoryType", "CategoryType", new {id = item.Id})');">view model</a>
				</td>
			</tr>
		}
	}
</table>

Presentation/Animal.Web/Views/CategoryType/GetCategoryType.cshtml
@model Entities.CategoryType

<table class="table table-bordered table-striped">
	<thead>
	<th class="p-3">ID</th>
	<th class="p-3">Name</th>
	<th class="p-3">Image</th>
	</thead>
	<tr>
		<td class="p-3">@Model.Id</td>
		<td class="p-3">@Model.CategoryName</td>
		<td class="p-3"><img style="width:30px;height:30px;" src="@Model.ImagePath" /></td>
	</tr>
</table>

Presentation/Animal.Web/Views/CategoryType/UpdateCategoryType.cshtml
@model ViewModel.CategoryType
@using Animal.Web.MediaComponents


@using (Html.BeginForm("UpdateCategoryType", "CategoryType", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = $"formSubmit('{Url.Action("UpdateCategoryType", "CategoryType")}', this, event);" }))
{
	@Html.AntiForgeryToken()
	<div>@Html.ValidationMessage("FormValidation")</div>

	@Html.TextInput(m=>m.Id)

	@Html.TextInput(m=>m.CategoryName)

	@Html.FileInput(m=>m.files)

	@Html.SubmitButton("Submit form")
}

Presentation/Animal.Web/Views/CategoryType/index.cshtml
<ul>
	<li class="nav-item h3">
		<a class="text-dark" href="javascript:changeMain('@Url.Action("GetAllCategories", "CategoryType")');">GetAllCategories</a>
	</li>
	<li class="nav-item h3">
		<a class="text-dark" href="javascript:changeMain('@Url.Action("GetCategoryType", "CategoryType", new {id = 0})');">GetCategoryType</a>
	</li>
	<li class="nav-item h3">
		<a class="text-dark" href="javascript:changeMain('@Url.Action("AddCategoryType", "CategoryType")');">AddCategoryType</a>
	</li>
	<li class="nav-item h3">
		<a class="text-dark" href="javascript:changeMain('@Url.Action("UpdateCategoryType", "CategoryType")');">UpdateCategoryType</a>
	</li>
	<li class="nav-item h3">
		<a class="text-dark" href="javascript:changeMain('@Url.Action("DeleteCategoryType", "CategoryType")');">DeleteCategoryType</a>
	</li>
</ul>