Presentation/Animal.Web/Controllers/FileUploadController.cs
using Entities;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;

namespace Animal.Web.Controllers
{
	public class FileUploadController : Base.AuthorizationController
	{
		public static IWebHostEnvironment _webHostEnvironment;
		private readonly IHttpContextAccessor _httpContextAccessor;

		public FileUploadController(IWebHostEnvironment webHostEnvironment, IHttpContextAccessor httpContextAccessor) : base(httpContextAccessor)
		{
			_webHostEnvironment = webHostEnvironment;
			_httpContextAccessor = httpContextAccessor;
		}
		public IActionResult Index()
		{
			return View();
		}

		[HttpGet]
		public IActionResult UploadFile()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult UploadFile(FileUpload fileUpload)
		{
			if (ModelState.IsValid)
			{
				try
				{
					if (fileUpload.files.Length > 0)
					{
						string path = _webHostEnvironment.WebRootPath + "\\FileUploads\\";
						if (!Directory.Exists(path))
						{
							Directory.CreateDirectory(path);
						}
						using (FileStream fileStream = System.IO.File.Create(path + fileUpload.files.FileName))
						{
							fileUpload.files.CopyTo(fileStream);
							fileStream.Flush();
							fileStream.Close();
						}
						//Success
						ModelState.AddModelError("FormValidation", "Success");
						return View();
					}
					else
					{
						ModelState.AddModelError("FormValidation", "empty or no file sent");
						return View(fileUpload);
					}
				}
				catch
				{
					ModelState.AddModelError("FormValidation", "an error has occured");
					return View(fileUpload);
				}
			}
			else
			{
				return View(fileUpload);
			}
		}

		[HttpGet]
		public IActionResult GetFile()
		{
			string path = _webHostEnvironment.WebRootPath + "\\FileUploads\\";
			string[] files = Directory.GetFiles(path);

			return View(files);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult GetFile(string FileName)
		{
			if(ModelState.IsValid)
			{
				string filePath = FileName;

				if (System.IO.File.Exists(filePath))
				{
					//Success
					var fileStream = new FileStream(filePath, FileMode.Open, FileAccess.Read);
					return new FileStreamResult(fileStream, "image/png");
				}
				else
				{
					ModelState.AddModelError("FormValidation", "file does not exist");
					return View(FileName);
				}
			}
			else
			{
				return View(FileName);
			}
		}
	}
}

Presentation/Animal.Web/Views/FileUpload/GetFile.cshtml
@model string[]
@using Animal.Web.MediaComponents


@using (Html.BeginForm("GetFile", "FileUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.AntiForgeryToken()
	<div>@Html.ValidationMessage("FormValidation")</div>

	<select name="FileName">
		<option disabled selected>Please select an option</option>

		@foreach(string item in Model)
		{
			<option value="@item">@item.Split("\\").Last()</option>
		}
	</select>

	@Html.SubmitButton("Submit form")
}

Presentation/Animal.Web/Views/FileUpload/Index.cshtml
<ul>
	<li class="nav-item h3">
		<a class="text-dark" href="javascript:changeMain('@Url.Action("UploadFile", "FileUpload")');">UploadFile</a>
	</li>
	<li class="nav-item h3">
		<a class="text-dark" href="javascript:changeMain('@Url.Action("GetFile", "FileUpload")');">GetFile</a>
	</li>
</ul>

Presentation/Animal.Web/Views/FileUpload/UploadFile.cshtml
@model Entities.FileUpload
@using Animal.Web.MediaComponents


@using (Html.BeginForm("UploadFile", "FileUpload", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = $"formSubmit('{Url.Action("UploadFile", "FileUpload")}', this, event);" }))
{
	@Html.AntiForgeryToken()
	<div>@Html.ValidationMessage("FormValidation")</div>

	@Html.FileInput(m=>m.files)

	@Html.SubmitButton("Submit form")
}