Presentation/Animal.Web/Controllers/AnimalController.cs
using Microsoft.AspNetCore.Mvc;

namespace Animal.Web.Controllers
{
	public class AnimalController : Base.AuthorizationController
	{
		private readonly IHttpContextAccessor _httpContextAccessor;
		public AnimalController(IHttpContextAccessor httpContextAccessor) : base(httpContextAccessor)
		{
			_httpContextAccessor = httpContextAccessor;
		}
		public IActionResult Index()
		{
			return View();
		}

		public IActionResult GetAnimal(int id)
		{
			if (id == 0)
			{
				return View(new Entities.Animal());
			}

			var obj = new AnimalProvider.Animal();
			Entities.Animal entity = obj.getAnimal(id);

			return View(entity);
		}

		public IActionResult GetAllAnimals()
		{
			var obj = new AnimalProvider.Animal();
			List<Entities.Animal> entityList = obj.getAllAnimals();

			return View(entityList);
		}

		[HttpGet]
		public IActionResult AddAnimal()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult AddAnimal(ViewModel.Animal animal)
		{
			if (ModelState.IsValid)
			{
				var obj = new AnimalProvider.Animal();
				if (obj.addAnimal(animal))
				{
					//Success
					ModelState.AddModelError("FormValidation", "Success");
					return View();
				}
				else
				{
					ModelState.AddModelError("FormValidation", "an error has occured");
					return View(animal);
				}
			}
			else
			{
				return View(animal);
			}
		}

		[HttpGet]
		public IActionResult UpdateAnimal()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult UpdateAnimal(ViewModel.Animal animal)
		{
			if (ModelState.IsValid)
			{
				using var Obj = new AnimalProvider.Animal();

				if (Obj.updateAnimal(animal))
				{
					//Success
					ModelState.AddModelError("FormValidation", "Success");
					return View();
				}
				else
				{
					ModelState.AddModelError("FormValidation", "an error has occured");
					return View(animal);
				}
			}
			else
			{
				return View(animal);
			}
		}

		[HttpGet]
		public IActionResult DeleteAnimal()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult DeleteAnimal(int id)
		{
			if (ModelState.IsValid)
			{
				using var obj = new AnimalProvider.Animal();
				if (obj.deleteAnimal(id))
				{
					//Success
					ModelState.AddModelError("FormValidation", "Success");
					return View();
				}
				else
				{
					ModelState.AddModelError("FormValidation", "an error has occured");
					return View(id);
				}
			}
			else
			{
				return View(id);
			}
		}
	}
}

Presentation/Animal.Web/Controllers/ChatController.cs
using Animal.Web.Hubs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;

namespace Animal.Web.Controllers
{
    public class ChatController : Base.UserController
	{
		private readonly IHttpContextAccessor _httpContextAccessor;
		public ChatController(IHttpContextAccessor httpContextAccessor) : base(httpContextAccessor)
		{
			_httpContextAccessor = httpContextAccessor;
		}
		public IActionResult Index()
		{
			using var obj = new AnimalProvider.Message();
            List<Entities.Message> messages = obj.getGlobalMessages();

			var tuple = new Tuple<List<Entities.Message>, Entities.User>(messages, CurrentUser);

            return View(tuple);
		}

		public IActionResult PrivateChat(int id, string username, string connectionID)
		{
			var obj = new AnimalProvider.Message();
			List<Entities.PrivateMessage> messages = obj.getPrivateMessages(CurrentUser.Id, id);

			var tuple = new Tuple<List<Entities.PrivateMessage>, int, string, string?, int>(messages, id, username, connectionID, CurrentUser.Id);

			return View(tuple);
		}

		public IActionResult sendGlobalMessage(int senderID, string text)
		{
            using var obj = new AnimalProvider.Message();
            if (obj.sendGlobalMessage(senderID, text))
            {
                return Ok("sent");
            }
            else
            {
                return BadRequest("an error has occured");
            }
        }

        public IActionResult sendPrivateMessage(int senderID, int receiverID, string text)
		{
            using var obj = new AnimalProvider.Message();
            if (obj.sendPrivateMessage(senderID, receiverID, text))
            {
                return Ok("Message sent");
            }
            else
            {
                return BadRequest("an error has occured");
            }
        }

        public IActionResult sideBar()
        {
            List<string> onlineUsernames = new List<string>();
            onlineUsernames.Add(CurrentUser.Name);

            foreach (var user in ChatHub.users)
            {
                onlineUsernames.Add((string)user.Items["username"]);
            }

            using var obj = new AnimalProvider.Users();
            List<Entities.User> users = obj.getAllUsers();

            List<Entities.User> offlineUsers = new List<Entities.User>();
            foreach (var item in users)
            {
                if (!onlineUsernames.Contains(item.Name))
                {
                    offlineUsers.Add(item);
                }
            }

            var tuple = new Tuple<List<HubCallerContext>, List<Entities.User>>(ChatHub.users, offlineUsers);

            return PartialView(tuple);
        }
    }
}

Presentation/Animal.Web/Controllers/LoginController.cs
using Animal.Web.MediaComponents;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Animal.Web.Controllers
{
	public class LoginController : Base.BaseController
	{
		[HttpGet]
		public IActionResult Index()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Index(ViewModel.Login model)
		{
			if (ModelState.IsValid)
			{
				var data = new AnimalProvider.Users().getUserByInfo(model.Name);

				if (data == null)
				{
					ModelState.AddModelError("FormValidation", "Wrong Username");
					return View(model);
				}

				if (!(new PasswordHasher().verify(data.password, model.Password)))
				{
					ModelState.AddModelError("FormValidation", "Wrong Password");
					return View(model);
				}

				var varClaims = new ClaimsPrincipal(new ClaimsIdentity(new[]
				{
					new Claim("Id", data.Id.ToString()),
					new Claim(ClaimTypes.Name, data.Name),
					new Claim(ClaimTypes.Email, data.Email),
					new Claim(ClaimTypes.DateOfBirth, data.DateOfBirth),
					new Claim(ClaimTypes.Role, data.role)
				}, "Custom"));

				var authProperties = new AuthenticationProperties
				{
					IsPersistent = true,
					ExpiresUtc = DateTime.UtcNow.AddMinutes(60),
					AllowRefresh = true,
				};

				await HttpContext.SignInAsync(varClaims, authProperties);
			}
			else
			{
				return View(model);
			}

			//Success
			return RedirectToAction("Index", "Home");
		}

		public async Task<IActionResult> Logout()
		{
			await HttpContext.SignOutAsync();
			return RedirectToAction("Index", "Home");
		}


		[HttpGet]
		public IActionResult Register()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Register(ViewModel.Register model)
		{
			if (ModelState.IsValid)
			{
				using var obj = new AnimalProvider.Users();
				model.Password = new PasswordHasher().hash(model.Password);

				if (obj.registerUser(model))
				{
					var data = new AnimalProvider.Users().getUserByInfo(model.Name);

					var varClaims = new ClaimsPrincipal(new ClaimsIdentity(new[]
					{
					new Claim("Id", data.Id.ToString()),
					new Claim(ClaimTypes.Name, data.Name),
					new Claim(ClaimTypes.Email, data.Email),
					new Claim(ClaimTypes.DateOfBirth, data.DateOfBirth),
					new Claim(ClaimTypes.Role, data.role)
						}, "Custom"));

					var authProperties = new AuthenticationProperties
					{
						IsPersistent = true,
						ExpiresUtc = DateTime.UtcNow.AddMinutes(60),
						AllowRefresh = true,
					};

					await HttpContext.SignInAsync(varClaims, authProperties);

					return RedirectToAction("Index", "Home");
				}
				else
				{
					ModelState.AddModelError("FormValidation", "an error has occured");
					return View(model);
				}
			}
			else
			{
				return View(model);
			}
		}
	}
}

Presentation/Animal.Web/Controllers/UserController.cs
using Animal.Web.Base;
using Microsoft.AspNetCore.Mvc;

namespace Animal.Web.Controllers
{
	public class UserController : Base.UserController
	{
		private readonly IHttpContextAccessor _httpContextAccessor;
		public UserController(IHttpContextAccessor httpContextAccessor) : base(httpContextAccessor)
		{
			_httpContextAccessor = httpContextAccessor;
		}
		[CustomAuthorize("admin", "superAdmin")]
		public IActionResult Index()
		{
			return View();
		}

		[CustomAuthorize("admin", "superAdmin")]
		public IActionResult GetAllUsers()
		{
			var obj = new AnimalProvider.Users();
			var objList = obj.getAllUsers();
			return View(objList);
		}

		[CustomAuthorize("admin", "superAdmin")]
		public IActionResult GetUser(int id)
		{
			if (id == 0)
			{
				return View(new Entities.User());
			}
			var obj = new AnimalProvider.Users();
			var model = obj.getUser(id);
			return View(model);
		}

		public IActionResult GetCurrentUser()
		{
			var obj = new AnimalProvider.Users();
            var model = obj.getUser(CurrentUser.Id);
            return View("GetUser", model);
        }

		[HttpGet]
		[CustomAuthorize("admin", "superAdmin")]
		public IActionResult AddUser()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[CustomAuthorize("admin", "superAdmin")]
		public IActionResult AddUser(ViewModel.User user)
		{
			if (ModelState.IsValid)
			{
				using var obj = new AnimalProvider.Users();
				if (obj.addUser(user))
				{
					//Success
					ModelState.AddModelError("FormValidation", "Success");
					return View();
				}
				else
				{
					ModelState.AddModelError("FormValidation", "an error has occured");
					return View(user);
				}
			}
			else
			{
				return View(user);
			}
		}

		[HttpGet]
		[CustomAuthorize("admin", "superAdmin")]
		public IActionResult UpdateUser() 
		{ 
			return View(); 
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[CustomAuthorize("admin", "superAdmin")]
		public IActionResult UpdateUser(ViewModel.User user) 
		{
			if (ModelState.IsValid)
			{
				using var obj = new AnimalProvider.Users();
				if (obj.updateUser(user))
				{
					//Success
					ModelState.AddModelError("FormValidation", "Success");
					return View();
				}
				else
				{
					ModelState.AddModelError("FormValidation", "an error has occured");
					return View(user);
				}
			}
			else
			{
				return View(user);
			}
		}

		[HttpGet]
		[CustomAuthorize("admin", "superAdmin")]
		public IActionResult DeleteUser()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[CustomAuthorize("admin", "superAdmin")]
		public IActionResult DeleteUser(int id) 
		{
			if (ModelState.IsValid)
			{
				using var obj = new AnimalProvider.Users();
				if (obj.deleteUser(id))
				{
					//Success
					ModelState.AddModelError("FormValidation", "Success");
					return View();
				}
				else
				{
					ModelState.AddModelError("FormValidation", "an error has occured");
					return View(id);
				}
			}
			else
			{
				return View(id);
			}
		}
	}
}

Presentation/Animal.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Animal Project</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Animal.Web.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" href="javascript:changeMain('@Url.Action("Index", "Home")');">Animal.Web</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark text-underline-hover" href="javascript:changeMain('@Url.Action("Index", "Home")');">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" href="javascript:changeMain('@Url.Action("Privacy", "Home")');">Privacy</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" href="javascript:changeMain('@Url.Action("Index", "Animal")');">Animal</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" href="javascript:changeMain('@Url.Action("Index", "CategoryType")');">categoryType</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" href="javascript:changeMain('@Url.Action("Index", "User")');">User</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" href="javascript:changeMain('@Url.Action("Index", "FileUpload")');">FileUpload</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" href="javascript:changeMain('@Url.Action("Index", "Chat")');">Chat</a>
						</li>
					</ul>

					@if (User.Identity.IsAuthenticated)
					{
						<a class="nav-link text-dark float-end" asp-controller="Login" asp-action="Logout">Logout</a>
						<a class="nav-link text-dark float-end" href="javascript:changeMain('@Url.Action("GetCurrentUser", "User")');">User Details</a>
					}
					else
					{
						<a class="nav-link text-dark float-end" href="javascript:changeMain('@Url.Action("Index", "Login")');">Login</a>
					}
				</div>
			</div>
		</nav>
	</header>

	<div class="container">
		<button class="border-0 rounded position-absolute d-flex m-0" style="background-color: #f2f2f2; padding: 10px 15px;" onclick="history.back();">
			<span style="border-top: 8px solid transparent; border-bottom: 8px solid transparent; border-right: 8px solid;"></span>
		</button>
		<main role="main" class="px-5">
			<div id="level1">
				@RenderBody()
			</div>
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2023 - Animal.Web - <a asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="~/js/Ajax.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>